name: PHP Composer

on:
  push:
    branches: 
      - master
      - test
  pull_request:
    branches:
      - master
      - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: docker-compose run --rm composer validate

    - name: Composer install
      run: docker-compose run --rm composer install

    - name: PHP STAN
      run: docker-compose run --rm composer run-script phpstan

    - name: PHP UNIT
      run: docker-compose run --rm composer run-script test