name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Stack
      run: docker-compose up -d app db

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Run test suite
      run: composer run-script test

    - name: Run PHPSTAN
      run: composer run-script phpstan
